CREATE TABLE `airline` (
  `FLIGHT_CODE` int(5) NOT NULL,
  `AIRLINE_ID` varchar(10) NOT NULL,
  `AIRLINE_NAME` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `airport` (
  `A_NAME` varchar(50) NOT NULL,
  `STATE` varchar(30) NOT NULL,
  `COUNTRY` varchar(30) NOT NULL,
  `C_NAME` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `city` (
  `C_NAME` varchar(30) NOT NULL,
  `STATE` varchar(30) NOT NULL,
  `COUNTRY` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `contains` (
  `A_NAME` varchar(50) DEFAULT NULL,
  `AIRLINE_ID` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `flight` (
  `SOURCE` varchar(50) NOT NULL,
  `DESTINATION` varchar(50) NOT NULL,
  `DEPARTURE` varchar(20) DEFAULT NULL,
  `ARRIVAL` varchar(20) DEFAULT NULL,
  `DURATION` varchar(20) DEFAULT NULL,
  `FLIGHT_CODE` char(10) NOT NULL,
  `AIRLINE_ID` varchar(10) DEFAULT NULL,
  `PRICE_BUSINESS` int(15) DEFAULT NULL,
  `PRICE_ECONOMY` int(15) DEFAULT NULL,
  `PRICE_STUDENTS` int(15) DEFAULT NULL,
  `PRICE_DIFFERENTLYABLED` int(15) DEFAULT NULL,
  `DATE` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `pass` (
  `PASSPORT_NO` char(8) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `passenger` (
  `FNAME` varchar(50) NOT NULL,
  `MNAME` varchar(50) DEFAULT NULL,
  `LNAME` varchar(50) NOT NULL,
  `PASSPORT_NO` char(8) NOT NULL,
  `AGE` int(3) DEFAULT NULL,
  `SEX` char(1) DEFAULT NULL,
  `PHONE` char(10) DEFAULT NULL,
  `ADDRESS` varchar(50) DEFAULT NULL,
  `FLIGHT_CODE` char(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `price` (
  `PRICE` int(20) DEFAULT NULL,
  `TYPE` char(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `selected` (
  `FLIGHT_CODE` char(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `ticket` (
  `TICKET_NO` int(11) NOT NULL,
  `PRICE` int(15) DEFAULT NULL,
  `SOURCE` varchar(30) DEFAULT NULL,
  `DESTINATION` varchar(30) DEFAULT NULL,
  `DATE_OF_TRAVEL` date DEFAULT NULL,
  `PASSPORT_NO` char(8) DEFAULT NULL,
  `FLIGHT_CODE` char(10) DEFAULT NULL,
  `TYPE` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `airline`
  ADD PRIMARY KEY (`FLIGHT_CODE`);

ALTER TABLE `airport`
  ADD PRIMARY KEY (`A_NAME`);

ALTER TABLE `city`
  ADD PRIMARY KEY (`C_NAME`);

ALTER TABLE `flight`
  ADD PRIMARY KEY (`FLIGHT_CODE`);

ALTER TABLE `passenger`
  ADD PRIMARY KEY (`PASSPORT_NO`);

ALTER TABLE `ticket`
  ADD PRIMARY KEY (`TICKET_NO`);

ALTER TABLE `ticket`
  MODIFY `TICKET_NO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;
COMMIT;